org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false

# AppLens uses no AndroidX / Jetifier artifacts.
android.useAndroidX=false
android.enableJetifier=false
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.suppressUnsupportedCompileSdk=34
